[package]
name = "rust-orgmode-derive"
version = "0.1.0"
authors = ["Matthias Seiffert <lythenas@hotmail.de>"]

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
proc-macro2 = "0.4"

[dependencies.syn]
version = "0.15"
features = ["extra-traits"]
